name: Build lk2nd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the repository
      - name: Clone lk2nd repository
        run: |
          git clone https://github.com/msm8916-mainline/lk2nd.git
          cd lk2nd
          
      # Step 2: Find the project folder and extract the relevant mk file
      - name: Find the mk file and extract 'xxxx'
        run: |
          cd lk2nd/project
          # Find all mk files in the project folder that match the pattern 'lk2nd-xxxx.mk'
          mk_file=$(find . -type f -name "lk2nd-*.mk" | head -n 1)
          if [ -z "$mk_file" ]; then
            echo "No mk file found matching the pattern lk2nd-xxxx.mk"
            exit 1
          fi
          # Extract 'xxxx' from the file name using regex
          if [[ "$mk_file" =~ lk2nd-(.*)\.mk ]]; then
            echo "Found mk file: $mk_file"
            version="${BASH_REMATCH[1]}"
            echo "Version: $version"
          else
            echo "No matching mk file found"
            exit 1
          fi
          
      # Step 3: Build lk2nd
      - name: Build lk2nd
        run: |
          cd lk2nd
          make TOOLCHAIN_PREFIX=arm-none-eabi- lk2nd-msm$version
