name: Build ARM64 Kernel

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'GitHub repository URL to clone the kernel source from'
        required: true
        default: 'https://github.com/barni2000/linux.git'
      CLANG_URL:
        description: 'Clang URL'
        required: true
        default: 'https://github.com/XSans0/WeebX-Clang/releases/download/WeebX-Clang-19.1.0-rc2-release/WeebX-Clang-19.1.0-rc2.tar.gz'  
      branch:
        description: 'Branch of the repository to use'
        required: true
        default: 'msm89x7-6.9-rc6-playground'
      defconfig:
        description: 'Defconfig file to use for the build'
        required: true
        default: 'msm8937_pmos_defconfig'
      dtb:
        description: 'dtb'
        required: true
        default: 'msm8917-xiaomi-rolex.dtb'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu bc bison flex libssl-dev make kernel-package
        sudo apt install binfmt-support qemu-user-static gcc-10-aarch64-linux-gnu fakeroot simg2img img2simg mkbootimg bison flex gcc-aarch64-linux-gnu pkg-config libncurses-dev libssl-dev unzip git

    - name: Download and extract Clang
      run: |
        mkdir clang
        wget -q ${{ github.event.inputs.CLANG_URL }} -O clang.tar.gz
        tar -C clang/ -zxf clang.tar.gz
        export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH
        ldd --version

    - name: Check clang version
      run: |
        clang --version

    - name: Clone the kernel source
      run: |
        mkdir linux-kernel
        cd linux-kernel
        git clone --branch ${{ github.event.inputs.branch }} ${{ github.event.inputs.repository }} kernel-src
        cd kernel-src

    - name: Build the kernel
      run: |
        cd linux-kernel/kernel-src
        export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=clang ${{ github.event.inputs.defconfig }}
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=clang -j$(nproc)
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=clang deb-pkg -j$(nproc)
    
    # - name: Build the kernel deb
    #   run: |
    #     cd linux-kernel/kernel-src
    #     fakeroot make-kpkg  --initrd --cross-compile aarch64-linux-gnu- --arch arm64 kernel_image kernel_headers

    - name: Upload the kernel image
      uses: actions/upload-artifact@v3
      with:
        name: Image.gz
        path: linux-kernel/kernel-src/arch/arm64/boot/Image.gz

    - name: Upload the dtb
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.inputs.dtb }}
        path: linux-kernel/kernel-src/arch/arm64/boot/${{ github.event.inputs.dtb }}

    - name: Upload the linux-headers-*.deb
      uses: actions/upload-artifact@v3
      with:
        name: linux-headers.deb
        path: linux-kernel/linux-headers-*.deb

    - name: Upload the linux-image-*.deb
      uses: actions/upload-artifact@v3
      with:
        name: linux-image.deb
        path: linux-kernel/linux-image-*.deb
